name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: yarn install, lint, test and build
      run: |
        yarn install
        yarn lint
        yarn test
        yarn build
      env:
        CI: true
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.2
      env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO --delete --exclude 'logs' --exclude 'node_modules' --exclude 'dist' --exclude 'env/*.env' --exclude '.git' --exclude '.github'"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}    
    - name: Relaunch Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          cd $${{ secrets.REMOTE_TARGET }}
          yarn install && yarn build
